import Service from '@ember/service';

export default Service.extend({
  dataset: 'database',
  series: 'list',
  nonGeographicDataset: 'bar-chart',
  feature: 'map-pin',
  software: 'monitor',
  service: 'handshake',
  model: 'box',
  tile: 'layers',
  metadata: 'logs',
  initiative: 'clipboard-checked',
  sample: 'beaker',
  document: 'file-text',
  repository: 'database',
  aggregate: 'map',
  collection: 'collections',
  coverage: 'bank-vault',
  application: 'code',
  sciencePaper: 'beaker',
  userGuide: 'support',
  dataDictionary: 'docs',
  website: 'globe-private',
  publication: 'file-text',
  report: 'file-text',
  awardInfo: 'certificate',
  collectionSite: 'map-pin',
  project: 'wrench',
  factSheet: 'file',
  tabularDataset: 'list',
  map: 'map',
  drawing: 'edit',
  photographicImage: 'camera',
  presentation: 'files',
  defaultFile: 'file',
  defaultList: 'chevron-right',
  individuals: 'user',
  organizations: 'users',
});
