import Service from '@ember/service';

export default Service.extend({
  dataset: 'globe',
  series: 'list',
  nonGeographicDataset: 'bar-chart',
  feature: 'map-pin',
  software: 'monitor',
  service: 'handshake',
  model: 'box',
  tile: 'grid',
  metadata: 'file-source',
  initiative: 'clipboard-checked',
  sample: 'beaker',
  document: 'file-change',
  repository: 'database',
  aggregate: 'network',
  collection: 'files',
  coverage: 'thumbs-up',
  application: 'file-source',
  sciencePaper: 'beaker',
  userGuide: 'guide',
  dataDictionary: 'docs',
  website: 'smartphone',
  publication: 'file-check',
  report: 'archive',
  awardInfo: 'certificate',
  collectionSite: 'map-pin',
  project: 'wrench',
  factSheet: 'file-check',
  tabularDataset: 'grid',
  map: 'map',
  drawing: 'image',
  photographicImage: 'camera',
  presentation: 'line-chart-up',
  defaultFile: 'file',
  defaultList: 'chevron-right',
  individuals: 'user',
  organizations: 'users',
});
