version: '3.7'

services:
    app:
        image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        networks:
            - default
            - proxy_default
        deploy:
            labels:
              - traefik.enable=true
              - traefik.docker.network=proxy_default
              - traefik.frontend.rule=Host:mdeditor.djcase.com
              - traefik.frontend.passHostHeader=true
              - traefik.port=8043
              - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.permanent=true"
              - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.regex=^https?://www\\.(.+)"
              - "traefik.http.middlewares.redirect-www-to-non-www.redirectregex.replacement=https://$${1}"
networks:
    proxy_default:
        external: true
    default:
        driver: overlay
        attachable: true
