export default function () {
  this.transition(
    this.toRoute('record.show.edit.main.citation'),
    this.fromRoute('record.show.edit.main.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.main.citation.identifier'),
    this.fromRoute('record.show.edit.main.citation.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.identifier'),
    this.fromRoute('record.show.edit.metadata.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.alternate'),
    this.fromRoute('record.show.edit.metadata.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.alternate.identifier'),
    this.fromRoute('record.show.edit.metadata.alternate.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.parent'),
    this.fromRoute('record.show.edit.metadata.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.parent.identifier'),
    this.fromRoute('record.show.edit.metadata.parent.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.lineage.lineageobject'),
    this.fromRoute('record.show.edit.lineage.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.lineage.lineageobject.citation'),
    this.fromRoute('record.show.edit.lineage.lineageobject.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.lineage.lineageobject.citation.identifier'),
    this.fromRoute('record.show.edit.lineage.lineageobject.citation.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.lineage.lineageobject.step'),
    this.fromRoute('record.show.edit.lineage.lineageobject.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.lineage.lineageobject.step.citation'),
    this.fromRoute('record.show.edit.lineage.lineageobject.step.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.associated.resource'),
    this.fromRoute('record.show.edit.associated.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.documents.citation'),
    this.fromRoute('record.show.edit.documents.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
}
