export default function() {
  this.transition(
    this.toRoute('record.show.edit.main.citation'),
    this.fromRoute('record.show.edit.main.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.main.citation.identifier'),
    this.fromRoute('record.show.edit.main.citation.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.identifier'),
    this.fromRoute('record.show.edit.metadata.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.alternate'),
    this.fromRoute('record.show.edit.metadata.index'),
    this.use('toLeft'),
    this.reverse('toRight')
    //,this.debug()
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.parent'),
    this.fromRoute('record.show.edit.metadata.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('record.show.edit.metadata.parent.identifier'),
    this.fromRoute('record.show.edit.metadata.parent.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
}
